permalink: /posts/:title
markdown: kramdown
kramdown:
  auto_ids: false
  enable_coderay: false

domain: sceditor.com
title: SCEditor
author: Sam Clarke
email: sam@samclarke.com

disqus:
  id: sceditor

github:
  username: samclarke

sceditor:
  version: 1.4.3
  download: http://www.sceditor.com/latest.zip

paginate: 10
