permalink: /posts/:title
markdown: kramdown
kramdown:
  auto_ids: false
  enable_coderay: false

domain: sceditor.com
title: SCEditor
author: Sam Clarke
email: sam@samclarke.com

relative_permalinks: false

disqus:
  id: sceditor

github:
  username: samclarke

exclude: [build]

sceditor:
  version: 1.4.4
  download: http://www.sceditor.com/latest.zip

paginate: 10
paginate_path: "posts/page:num"
