baseURL: "https://www.sceditor.com/"
languageCode: "en-us"
title: "SCEditor"
theme: "sceditor"

paginate: 10
paginatePath: ""

permalinks:
  - post: /posts/:title

params:
  downloadUrl: "https://github.com/samclarke/SCEditor/releases/download/v2.1.2/sceditor-2.1.2.zip"
